# Generated by Django 3.0.7 on 2020-06-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200627_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_type',
            field=models.CharField(choices=[('Client', 'I am a Client'), ('Tutor', 'I am a Tutor')], default=1, max_length=80),
        ),
    ]
