# Generated by Django 3.0.7 on 2020-06-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200629_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_education_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_price_per_hour',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_subject_primary',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_subject_primary_other',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_subject_secondary',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_subject_secondary_other',
        ),
    ]
