# Generated by Django 3.0.7 on 2020-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200627_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
