# Generated by Django 3.0.7 on 2020-06-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200628_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
