# Generated by Django 3.0.7 on 2020-06-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_userprofile_default_image_url'),
        ('profiles', '0008_auto_20200629_1532'),
    ]

    operations = [
    ]
