# Generated by Django 3.0.7 on 2020-06-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200629_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_type',
        ),
    ]
