# Generated by Django 3.0.7 on 2020-06-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='price_per_hour',
            new_name='krona_per_hour',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='primary_subject',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='tutor',
            name='education',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
