# Generated by Django 3.0.7 on 2020-06-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20200629_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='rating',
        ),
    ]
