# Generated by Django 3.0.7 on 2020-06-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_remove_tutor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
