# Generated by Django 3.0.7 on 2020-06-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_tutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='hours_hired',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
    ]
