# Generated by Django 3.0.7 on 2020-06-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_auto_20200630_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='hours',
        ),
    ]
